### ISSUE TITLE
Rerun error'ed dataset / job using bioblend API

### ISSUE THREAD

**Issue by edwardsnj** [galaxyproject/bioblend#277]
I am invoking workflows using the bioblend API, but occasionally a job will fail and I need to rerun it. I currently have to log into the Galaxy instance and use the "rerun" button, remember to check the resume dependent jobs checkbox, and click submit. I'd like to automate the process. 

More than just invoking run_tool with params and inputs from the job state, I need to "replace" the job in the workflow invocation, and unpause its dependent datasets/jobs. 

How can I accomplish this using the API? 

Thanks,

- n

**Comment by nsoranzo** [comment]
@edwardsnj Thanks for opening an issue. Unfortunately this is not supported by the Galaxy API yet, see for reference https://github.com/galaxyproject/galaxy/pull/7333 .

**Comment by mvdbeek** [comment]
@nsoranzo you can do this using the API, you first GET to `api/job/<job_id>/build_for_rerun` and then POST using those parameters. We could add a method to bioblend to do that (that's also what the UI does).

**Comment by edwardsnj** [comment]
Not sure what the recommended strategy for hitting the jobs controller for this api call, but something like this?

        url = '/'.join(["api", "job", job_id, "build_for_rerun"])
        rerun_details = gi._get(url=url)
        # hoping this will just work?!?!?!?!!?
        gi.tools.run_tool(**rerun_details)

Will that do the other steps (unpausing paused jobs, and replacing the error'ed job in the history) too?

Thanks,

- n

**Comment by edwardsnj** [comment]
OK, experimenting a bit (there is probably a better way to make the url...)

          url = gi._make_url(gi.jobs)
          url = '/'.join([url, ji.get('id'), "build_for_rerun"])
          rerun_details = gi.jobs._get(url=url)

gets me a rerun_details dictionary with two (probably) key items: action=/tool_runner/index, and remap_job=False. However, /tool_runner/index is just in charge of displaying the tool form if I interpret the source code correctly. Can I use gi.tools.run_tool to submit the rerun request if I pick out the important parts of rerun_details?

**Comment by edwardsnj** [comment]
remap_job == True gets turned into the "resume paused jobs" in the form, which then makes a checkbox parameter __rerun_remap_job_id__ with value the job_id of the job being rerun. I presume that this is what does the "replacing" step. The job details seems to have the input parameters, perhaps I can just get them from there? If so, what do I need build_for_rerun for?

**Comment by mvdbeek** [comment]
That's the idea, roughly, but it's a little more complicated. I'll have a look in the coming days.

**Comment by edwardsnj** [comment]
Any update on this? Or is this resolved by #7333?

**Comment by nsoranzo** [comment]
It's not solved AFAIK, galaxyproject/galaxy#7333 was not accepted.

**Comment by simonbray** [comment]
Would be great if this can be added to the API at some point, having to potentially rerun hundreds of failed jobs could be pretty painful.

**Comment by simonbray** [comment]
The following works for me:
```
job_id = ...
job_params = gi.jobs.show_job('{}/build_for_rerun'.format(job_id)) 
inputs = job_params['state_inputs'] 
inputs['rerun_remap_job_id'] = job_id 
gi.tools.run_tool(job_params['history_id'], job_params['id'], inputs)
```
which is great! When did this become possible, I assume since https://github.com/galaxyproject/galaxy/pull/9802?

A bioblend convenience function such as `gi.jobs.rerun_job()` would be a really nice next step. (Also, implementing a proper `build_for_rerun` parameter for the `show_job` method.)
